# cluster_config.yaml - cluster configuration
__default__:
    account: rpp-rieseber
    time: 0-0:45:00 # time limit for each job
    nodes: 1
    ntask: 1
    cpus: 4
    mem: 120G
    output: default-%j.out #stdoutput.
    error: default-%j.err #stdoutput error
    
Init:
    time: 0-0:30:00 # time limit for each job
    output: Init-%j.out #stdoutput. 
    error: Init-%j.err #stdoutput error

Chr_splitting:
    time: 0-0:30:00 # time limit for each job
    output: Chr_splitting-%j.out #stdoutput. 
    error: Chr_splitting-%j.err #stdoutput error

EDTA_individual:
    time: 0-35:45:00 # time limit for each job
    output: EDTA_individual-%j.out #stdoutput. 
    error: EDTA_individual-%j.err #stdoutput error
    cpus: 16
    mem: 120G

Masked_FASTA:
    time: 0-2:30:00 # time limit for each job
    output: Masked_FASTA-%j.out #stdoutput. 
    error: Masked_FASTA-%j.err #stdoutput error
    cpus: 1
    
STEP1_annotation:
    time: 0-2:30:00 # time limit for each job
    output: STEP1_annotation-%j.out #stdoutput. 
    error: STEP1_annotation-%j.err #stdoutput error
    cpus: 2
    mem: 120G

STEP2_annotation:
    time: 0-5:30:00 # time limit for each job
    output: STEP2_annotation-%j.out #stdoutput. 
    error: STEP2_annotation-%j.err #stdoutput error
    cpus: 4
    mem: 120G
    
Chr_merge:
    time: 0-0:30:00 # time limit for each job
    output: Chr_merge-%j.out #stdoutput. 
    error: Chr_merge-%j.err #stdoutput error
    cpus: 1 
    
GFF3_statistics:
    time: 0-2:45:00 # time limit for each job
    output: GFF3_statistics-%j.out #stdoutput. 
    error: GFF3_statistics-%j.err #stdoutput error
    cpus: 16

Chr_merge:
    time: 0-0:30:00 # time limit for each job
    output: Chr_merge-%j.out #stdoutput. 
    error: Chr_merge-%j.err #stdoutput error
    cpus: 1 

Summary_statistics:
    time: 0-1:45:00 # time limit for each job
    output: Summary_statistics-%j.out #stdoutput. 
    error: Summary_statistics-%j.err #stdoutput error
    cpus: 4

Summary_statistics_Original:
    time: 0-1:45:00 # time limit for each job
    output: Summary_statistics_Original-%j.out #stdoutput. 
    error: Summary_statistics_Original-%j.err #stdoutput error
    cpus: 4
      
BUSCO:
    time: 0-2:45:00 # time limit for each job
    output: BUSCO-%j.out #stdoutput. 
    error: BUSCO-%j.err #stdoutput error
    cpus: 16    

BUSCO_Original:
    time: 0-2:45:00 # time limit for each job
    output: BUSCO_Original-%j.out #stdoutput. 
    error: BUSCO_Original-%j.err #stdoutput error
    cpus: 16    
    